version: '3'

services:
  api:
    image: api
    tty: true
    volumes:
    - .:/app
    working_dir: /app
    ports:
      - 8080:8080
    command: bash -c "python mysite/manage.py migrate && python mysite/manage.py runserver 0.0.0.0:8080"
    environment:
      DOCKER_DB_HOST: db
      DOCKER_REDIS_HOST: redis
      DOCKER_HOST: api
  